name: Development actions

on:
  push:
    branches: ["development"]

jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        config: [
          { target: jvm, os: ubuntu-latest, tasks: jvmTest, continueOnError: false }
       ]
    runs-on: ${{ matrix.config.os }}
    name: Build ${{ matrix.config.target }}
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Test ${{ matrix.config.target }} targets
        continue-on-error: ${{ matrix.config.continueOnError }}
        run: ./gradlew ${{ matrix.config.tasks }}

  release:
      runs-on: macos-latest
      needs:
        - build
      steps:
        - uses: actions/checkout@v3

        - name: set up JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'temurin'

        - name: Setup gradle
          uses: gradle/gradle-build-action@v2

        - name: Publish to sonatype
          run: |
            ./gradlew publishAllPublicationsToMavenRepository \
            -PsonatypeUsername=${{ secrets.SONATYPE_USERNAME }} \
            -PsonatypePassword=${{ secrets.SONATYPE_PASSWORD }} \
            -PgpgKeySecret=$${{ secrets.GPG_KEY_SECRET }} \
            -PgpgKeyPassword=${{ secrets.GPG_KEY_PASSWORD }}
          env:
           SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
           SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
           GPG_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}
           GPG_KEY_SECRET: ${{ secrets.GPG_KEY_SECRET }}
